# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetIndCEScoresCPP <- function(yVec, muVec, lamVec, phiMat, SigmaYi) {
    .Call('_fdarep_GetIndCEScoresCPP', PACKAGE = 'fdarep', yVec, muVec, lamVec, phiMat, SigmaYi)
}

GetIndCEScoresCPPnewInd <- function(yVec, muVec, lamVec, phiMat, SigmaYi, newPhi, newMu) {
    .Call('_fdarep_GetIndCEScoresCPPnewInd', PACKAGE = 'fdarep', yVec, muVec, lamVec, phiMat, SigmaYi, newPhi, newMu)
}

